# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import serversmanage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1000)),
                ('ip', models.GenericIPAddressField()),
                ('serverstatus', models.CharField(default='Enabled', max_length=10)),
                ('backupstatus', models.CharField(max_length=200, null=True)),
                ('lastbackup', models.DateTimeField(null=True)),
                ('sshport', models.IntegerField(default=22)),
                ('backuppaths', models.TextField(default='/home,/usr/local/apache/conf,/etc/userdomains,/usr/local/apache/conf/php.conf,/etc/csf/csf.conf,/usr/local/lib/php.ini,/etc/my.cnf,/backup/cpbackup/daily,/var/lib/mysql', validators=[serversmanage.models.validate_backuppaths])),
            ],
        ),
    ]
