# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=17)),
                ('status', models.CharField(max_length=10)),
                ('backupstatus', models.CharField(max_length=200)),
                ('lastbackup', models.DateTimeField()),
            ],
        ),
    ]
