# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serversmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='status',
            new_name='serverstatus',
        ),
    ]
