# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversmanage', '0002_auto_20160707_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='backupstatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='lastbackup',
            field=models.DateTimeField(null=True),
        ),
    ]
