# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversmanage', '0003_auto_20160707_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='sshport',
            field=models.IntegerField(default=22),
        ),
    ]
