# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversmanage', '0004_servers_sshport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
