# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversmanage', '0005_auto_20160707_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='serverstatus',
            field=models.CharField(default='Enabled', max_length=10),
        ),
    ]
